name: typed_preferences
description: An expressive and type-safe wrapper around Shared Preferences with additional features like Observers and DAOs.
version: 0.1.0+1
maintainer: Yakov Karpov (@purplenoodlesoop)

homepage: https://github.com/purplenoodlesoop/typed-preferences

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=2.8.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.15
  meta: ^1.7.0

dev_dependencies:
  purple_lints: ^0.3.0
  test: ^1.16.0
