name: typed_preferences
description: A starting point for Dart libraries or applications.
version: 1.0.0

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=2.8.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.15
  meta: ^1.7.0

dev_dependencies:
  purple_lints: ^0.3.0
  test: ^1.16.0
